In [1]:
%%time

from basic.words import *

C:\ProgramData\Anaconda3\envs\entity_embedding\lib\site-packages\gensim\utils.py:1197: UserWarning: detected Windows; aliasing chunkize to chunkize_serial
  warnings.warn("detected Windows; aliasing chunkize to chunkize_serial")


-- loading 10000 word vectors from pretrained word2vec file at D:/_IUST/entity_embedding/data/cc.fa.300.vec... done!
-- forcing generate unigram!
-- generating unigram based on D:/_IUST/entity_embedding/data/fawiki-first-50000-docs.txt corpus... done!
-- generating powered unigram on 8857 words... done!
-- detecting stop words based on D:/_IUST/entity_embedding/data/fawiki-first-50000-docs.txt corpus... done!
Wall time: 28min 6s


In [2]:
%%time

from basic.entities import *

-- forcing generate entity id maps!
-- looking for entity articles in D:/_IUST/entity_embedding/data/fawiki-first-50000-docs.txt corpus... done!
   10000 entities added!
Wall time: 10.6 s


In [7]:
%%time

from data_gen import gen_wiki_canonical as can
from importlib import reload

reload(can)

# can.gen_canonical_words(can.fa_wiki_path, can.canonical_words_path)



-- starting first pass. 

NameError: name '_times' is not defined

In [8]:
%%time

from data_gen import gen_wiki_hyp_ctx as hyp
from importlib import reload

reload(hyp)

hyp.gen_wiki_hyp_ctx(hyp.fa_wiki_path, hyp.hyp_ctx_words_path, context_size=hyp.context_size)

-- generating hyperlink context data based on D:/_IUST/entity_embedding/data/fawiki-random-1000-docs.txt corpus... done!
Wall time: 22.4 s


In [21]:
%%time

from importlib import reload

from entity2vec import minibatch
import main 
from entity2vec import train

reload(minibatch)
reload(main)
reload(train)

train.train_entity_vectors(main.network, main.loss_func, main.optimizer, epochs=4)

# batch_count = 0
# for inputs, targets in minibatch.gen_minibatch():
#     batch_count += 1
#     print(minibatch._times)
#     if batch_count == 10:
#         break

-- starting 1-th epoch!
-- starting first pass. . . . . . . . . . . . . . . . . . . . . done!
-- starting 2-th pass on D:/_IUST/persian_entity_embedding/data/wiki-canonical-word-ids.txt. . . . . . . . . . . . . . . . . . . . . done!
-- starting 1-th pass on D:/_IUST/persian_entity_embedding/data/hyp-ctx-word-ids.txt. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .

In [19]:
wall_time = 15.8 
times_sum = 35.77
# sum(minibatch._times)
s = 0
for i in minibatch._times:
    s += i
s

12.599225759506226

In [8]:
from basic.words import *
from basic.entities import *

In [38]:
ent_names = ['قرآن', 'محمدرضا شجریان', 'تبریز', 'ارسطو', 'آلمان', 'اسلام', 'محمدرضا فروتن', 'شهاب حسینی', 'محمدرضا شفیعی کدکنی']

ent_ids = list(map(lambda e: wikiid2id[name2wikiid[e]], ent_names))

ent_ids = torch.Tensor(ent_ids).long()

embeddings = main.network.embedding(ent_ids).detach().numpy()

for i, e in enumerate(embeddings):

    similars = word2vec.similar_by_vector(e)
    words = []
    for s in similars:
        words.append(s[0])
        
    print(f'موجودیت «{ent_names[i]}» : کلمات {", ".join(words)}')

موجودیت «قرآن» : کلمات قرآن, روایات, کریم, احادیث, حدیث, آیات, سوره, قرآنی, سنت, یوسف
موجودیت «محمدرضا شجریان» : کلمات شجریان, آهنگساز, آهنگسازی, استاد, موسیقی, آواز, هنرمند, استادان, نوازنده, هنرمندان
موجودیت «تبریز» : کلمات تبریز, آذربایجان, هجری, Banbao, روستای, Shahre, دورهٔ, آذری, زادگاه, شهر
موجودیت «ارسطو» : کلمات فلسفه, فلسفی, فیلسوف, یونانی, نظریه, فرضیه, عقاید, منطق, اندیشه, مفهوم
موجودیت «آلمان» : کلمات آلمان, آلمانی, فرانسه, معمار, امپراتوری, مجارستان, اروپایی, اتریش, لهستان, آکادمی
موجودیت «اسلام» : کلمات اسلام, مسلمانان, مسیحیت, مذهب, سنت, مذاهب, دین, ادیان, مسلمان, تمدن
موجودیت «محمدرضا فروتن» : کلمات بازیگر, حاتمی, جواد, کارگردان, حمیدرضا, بازیگران, بهروز, مهسا, لیلا, کارگردانی
موجودیت «شهاب حسینی» : کلمات فیلم, بازیگر, سینمایی, کارگردان, فیلمی, داستان, هنرمند, فیلمهای, جشنواره, فرهادی
موجودیت «محمدرضا شفیعی کدکنی» : کلمات غلامحسین, محمدحسین, محمدرضا, محمود, علامه, حسین, غلامرضا, محمدعلی, اکبر, ابوالقاسم


In [34]:
first = word2vec.get_vector('محمدرضا')
second = word2vec.get_vector('فروتن')

word2vec.similar_by_vector((first + second)/2)

[('فروتن', 0.9123691320419312),
 ('محمدرضا', 0.7368292808532715),
 ('مسعود', 0.5714483261108398),
 ('رضا', 0.5569769144058228),
 ('جواد', 0.5502303838729858),
 ('مجید', 0.5325300693511963),
 ('محمد', 0.5321899652481079),
 ('حمیدرضا', 0.5263552069664001),
 ('شریفی', 0.5103566646575928),
 ('حمید', 0.5052734613418579)]

In [37]:
first = word2vec.get_vector('شهاب')
second = word2vec.get_vector('حسینی')

word2vec.similar_by_vector((first + second)/2)

[('شهاب', 0.9249618649482727),
 ('حسینی', 0.8233593702316284),
 ('مرادی', 0.554496705532074),
 ('کاظمی', 0.5367589592933655),
 ('مظفری', 0.536064088344574),
 ('حسین', 0.5333384871482849),
 ('اکبری', 0.5286636352539062),
 ('سید', 0.51639324426651),
 ('مهدی', 0.5141152143478394),
 ('کیوان', 0.5048292875289917)]

In [ ]:
ent_names = ['قرآن', 'محمدرضا شجریان', 'تبریز', 'ارسطو', 'آلمان', 'اسلام']

ent_ids = list(map(lambda e: wikiid2id[name2wikiid[e]], ent_names))

ent_ids = torch.Tensor(ent_ids).long()

embeddings = main.network.embedding(ent_ids).detach().numpy()

for i, e in enumerate(embeddings):

    similars = word2vec.similar_by_vector(e)
    words = []
    for s in similars:
        words.append(s[0])
        
    print(f'-- {ent_names[i]} is similar to : {", ".join(words)}')

In [1]:
import torch

In [3]:
model = torch.load('entity2vec/model.pickle')

C:\ProgramData\Anaconda3\envs\entity_embedding\lib\site-packages\gensim\utils.py:1197: UserWarning: detected Windows; aliasing chunkize to chunkize_serial
  warnings.warn("detected Windows; aliasing chunkize to chunkize_serial")


-- loading 100000 word vectors from pretrained word2vec file at D:/_IUST/entity_embedding/data/cc.fa.300.vec... done!
-- generating unigram based on D:/_IUST/entity_embedding/data/fawiki-first-50000-docs.txt corpus... done!
-- generating powered unigram on 61095 words... done!


In [31]:
t = torch.ones(5, 6).long()

In [41]:
t.mean(0)

RuntimeError: Can only calculate the mean of floating types. Got Long instead.

In [25]:
import torch
reload(torch)
torch.cuda.is_available()
device = torch.device('cuda:0')

In [29]:
s = 'بر اساس چهارچوب پروژه‌های چندزبانهٔ بنیادِ <a href="%D9%88%DB%8C%DA%A9%DB%8C%E2%80%8C%D9%85%D8%AF%DB%8C%D8%A7">ویکی‌مدیا</a>، در زبان فارسی نیز از یک نرم‌افزار ویکی استفاده شده‌است. برخی از پروژه‌های فارسیِ این بنیاد از این قرارند:'

In [34]:
from hazm import word_tokenize
from gensim.corpora import wikicorpus

ss = wikicorpus.filter_wiki(s)
sss = word_tokenize(ss)

stop_words = get_stop_words()
valid_words = list(filter(lambda w: w in word2id.keys(), sss))
pure_words = list(filter(lambda w: w not in stop_words, valid_words))

print('\t'.join(pure_words))

with open('text.txt', 'w', encoding='utf8') as f:
    f.write('\t'.join(pure_words))

اساس	پروژه‌های	زبان	فارسی	نرم‌افزار	ویکی	استفاده	شده‌است	پروژه‌های	بنیاد


In [6]:
import pickle

In [9]:
a = 'aa'
b = 'bbb'
c = 'cccc'

with open('test.pcl', 'wb') as f:
    pickle.dump(a, f)
    pickle.dump(b, f)
    pickle.dump(c, f)
    
with open('test.pcl', 'rb') as f:
    print(pickle.load(f))
    print(pickle.load(f))
    print(pickle.load(f))
    print(pickle.load(f))

aa
bbb
cccc


EOFError: Ran out of input

In [84]:
%%time
x = 0
for i in range(1500000):
    if str(i) in d1:
        x += 1
print(x)

1000000
Wall time: 2.36 s


In [85]:
%%time
x = 0
for i in range(1500000):
    if str(i) in d2:
        x += 1
print(x)

1000000
Wall time: 2.3 s


In [86]:
%%time
x = 0
for i in range(1500000):
    if str(i) in d1.keys():
        x += 1
print(x)

1000000
Wall time: 2.6 s


In [87]:
%%time
x = 0
for i in range(1500000):
    if str(i) in d2.keys():
        x += 1
print(x)

1000000
Wall time: 2.56 s


In [88]:
%%time
x = 0
for i in range(1500000):
    if i < len(l):
        x += 1
print(x)

1000000
Wall time: 1.19 s


In [3]:
import torch

In [45]:
x = torch.empty(7, 3).long()
tgs = torch.empty(7).long()
ids = torch.empty(100).long()
idxs = torch.empty(7).long()

for i in range(7):
    tgs[i] = i % 3
    idxs[i] = i+j
    for j in range(3):
        x[i][j] = 3*i+j

        
for i in range(100):
    ids[i] = 100 + i
x

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17],
        [18, 19, 20]])

In [50]:
ids[idxs]

tensor([102, 103, 104, 105, 106, 107, 108])

In [53]:
flat_idxs = torch.arange(0, 7)* 3 + tgs
flat_idxs

tensor([ 0,  4,  8,  9, 13, 17, 18])

In [70]:
x.put_(flat_idxs, ids[idxs])

tensor([[102,   1,   2],
        [  3, 103,   5],
        [103,   7, 104],
        [105,  10,  11],
        [104, 106,  14],
        [105,  16, 107],
        [108,  19,  20]])

In [5]:
import torch
import numpy as np

In [21]:
%%time

for i in range(500):
    np.random.choice(np.arange(10000), size=20, p=np.ones(10000) / 10000)

Wall time: 356 ms


In [23]:
%%time

for i in range(500):
    np.random.choice(np.arange(500000), size=20, p=np.ones(500000) / 500000)

Wall time: 17 s


In [65]:
from entity2vec import *

In [4]:
import multiprocessing
pool = multiprocessing.Pool(processes=4)

In [ ]:
pool.map()

In [4]:
batch_count = 0
for inputs, targets in minibatch.gen_minibatch():
	batch_count += 1

-- starting first pass. 

KeyboardInterrupt: 